[package]
name = "georust"
version = "0.1.0"
edition = "2021"

[dependencies]
proj = "0.6.0"
gdal = "0.14.0"

[dev-dependencies]
# Add your dev dependencies here

[build-dependencies]
# Add your build dependencies here
